# Generated by Django 6.1.1 on 2026-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_purchase_paid_amount_alter_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Utilities', 'Utilities (Electricity/Water/Net)'), ('Salaries', 'Salaries & Wages'), ('Maintenance', 'Maintenance & Repairs'), ('Packaging', 'Packaging & Supplies'), ('Transport', 'Transport & Shipping'), ('Marketing', 'Marketing & Ads'), ('Vendor Relations', 'Vendor Relations'), ('General', 'General / Other')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Paid', max_length=20),
        ),
    ]
